[package]
name = "gengir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8"
lazy_static = "1.4.0"
regex = "1.5.4"
if_chain = "1.0.2"